# Bellman for TicTacToe

In [5]:
import numpy as np
from typing import List
   
def bellman_v(v:np.ndarray, policy:List, Rsa:List, Psas:np.ndarray, 
        s:int=0, forgetting_factor:float=1.0) -> float:
    Gs = 0
    for a in range(len(policy[s])):
        Gs += policy[s][a] * bellman_q_by_v(v, Rsa, Psas, 
                s=s, a=a, forgetting_factor=forgetting_factor)
    return Gs

def bellman_q_by_v(v:np.ndarray, Rsa:List, Psas:np.ndarray, 
        s:int=0, a:int=0, forgetting_factor:float=1.0) -> float:
    reward = Rsa[s][a]
    v_next = 0
    for next_s in range(len(Psas[s,a])):
        if Psas[s,a,next_s] and next_s < len(v) - 1:
            v_next += Psas[s,a,next_s] * v[next_s]     
    Gs = reward + forgetting_factor * v_next
    return Gs

def bellman_q(q:List, policy:List, Rsa:List, Psas:np.ndarray, 
        s:int=0, a:int=0, forgetting_factor:float=1.0) -> float:
    reward = Rsa[s][a]
    v_next = 0
    for next_s in range(len(Psas[s,a])):
        if Psas[s,a,next_s] and next_s < len(q) - 1:
            v = 0
            for next_a in range(len(policy[next_s])):
                v += policy[next_s][next_a] * q[next_s][next_a]
            v_next += Psas[s,a,next_s] * v     
    Gs = reward + forgetting_factor * v_next
    return Gs

class MDP:
    def __init__(self):
        self.init_policy_Rsa()
        
    def init_policy_Rsa(self):
        # policy[state][action] = 0.9 (<-- prob)
        # None state is the last state        
        self.policy_actions_table = [['Facebook', 'Quit'], ['Facebook', 'Study'], 
            ['Sleep', 'Study'], ['Pub', 'Study'], None]
        self.Rsa = [[-1,0], [-1,-2], [0, -2], [1,10]]
        self.N_states = len(self.policy_actions_table)
        self.policy = []
        for actions in self.policy_actions_table:
            if actions:
                N_actions = len(actions)
                self.policy.append(np.ones(N_actions)/N_actions)
                
        # policy가 고려되지 않은 관계임. Policy에 따른 가중에 별도로 고려되어야 함.
        self.Psas = np.zeros([self.N_states, 2, self.N_states]) # Probability
        self.Psas[0,0,0], self.Psas[0,1,1] = 1.0, 1.0
        self.Psas[1,0,0], self.Psas[1,1,2] = 1.0, 1.0
        self.Psas[2,0,4], self.Psas[2,1,3] = 1.0, 1.0
        self.Psas[3,0,1], self.Psas[3,0,2], \
            self.Psas[3,0,3], self.Psas[3,1,4] = 0.2, 0.4, 0.4, 1.0 
        
    def init_v(self):
        self.v = np.zeros(self.N_states)
        
    def init_q(self):
        self.q = []
        for s in range(self.N_states - 1):
            self.q.append(np.zeros(len(self.policy[s])))
        self.q.append(0)
        
    def calc_bellman_v(self, s:int) -> float:
        return bellman_v(self.v, self.policy, self.Rsa, self.Psas, s=s)    
    
    def calc_bellman_q(self, s:int, a:int) -> float:
        #return 0
        return bellman_q(self.q, self.policy, self.Rsa, self.Psas, s=s, a=a)    
    
    def get_v(self, N_iter:int=10) -> np.ndarray:
        self.init_v()
        for n in range(N_iter):
            for s in range(self.N_states-1):
                self.v[s] = (self.v[s] * n + self.calc_bellman_v(s))/(n+1)        
        
        for s in range(self.N_states):
            print(f'v[{s}]={self.v[s]}')
        return self.v
    
    def get_q(self, N_iter:int=10) -> List:
        self.init_q()
        
        for n in range(N_iter):
            for s in range(self.N_states-1):
                for a in range(len(self.policy[s])):
                    #print(f'[?]s,a={s,a} --> {self.q[s][a]}')
                    self.q[s][a] = (self.q[s][a] * n + 
                        self.calc_bellman_q(s,a))/(n+1)  
                    #self.q[s][a] = (self.q[s][a] * n)/(n+1) 
        
        for s in range(self.N_states-1):
            for a in range(len(self.policy[s])):
                print(f'q[{s}][{a}]={self.q[s][a]}')
        return self.q      
    
    def test(self, N_Iter:int=100):
        print(f'Policy: {self.policy}')
        self.get_v(N_Iter)
        self.get_q(N_Iter)
             
MDP().test()

Policy: [array([0.5, 0.5]), array([0.5, 0.5]), array([0.5, 0.5]), array([0.5, 0.5])]
v[0]=-2.5057415905523253
v[1]=-1.6060272426565467
v[2]=2.4316473139847745
v[3]=7.135350237940245
v[4]=0.0
q[0][0]=-3.3266059231766705
q[0][1]=-1.6848772579279794
q[1][0]=-3.3516633390821924
q[1][1]=0.13960885376910126
q[2][0]=0.0
q[2][1]=4.863294627969549
q[3][0]=4.270700475880492
q[3][1]=10.0

In [6]:
import pandas as pd

In [18]:
S_df = pd.DataFrame({'S':[0,1,2,3,4]})
policy_df = pd.DataFrame({'s':[0,0,0,1,2,3], 'a':[0,1,2,0,0,0], 'pi':[1/3, 1/3, 1/3, 1, 1, 1]})
R_df = pd.DataFrame({'s':[0,0,0,1,2,3], 'a':[0,1,2,0,0,0], 'R':[1,0,-1/2,0,0,0]})
P_df = pd.DataFrame({'s':[0,0,0,0,0,1,2,3], 'a':[0,1,1,2,2,0,0,0], 'next_s':[4,1,2,3,4,4,4,4], 'P':[1,1/2,1/2,1/2,1/2,0,0,0]})

In [19]:
policy_df

   s  a        pi
0  0  0  0.333333
1  0  1  0.333333
2  0  2  0.333333
3  1  0  1.000000
4  2  0  1.000000
5  3  0  1.000000

In [20]:
R_df

   s  a    R
0  0  0  1.0
1  0  1  0.0
2  0  2 -0.5
3  1  0  0.0
4  2  0  0.0
5  3  0  0.0

In [21]:
P_df

   s  a  next_s    P
0  0  0       4  1.0
1  0  1       1  0.5
2  0  1       2  0.5
3  0  2       3  0.5
4  0  2       4  0.5
5  1  0       4  0.0
6  2  0       4  0.0
7  3  0       4  0.0

In [22]:
S_df

   S
0  0
1  1
2  2
3  3
4  4

In [32]:
for a in set(P_df[P_df.s == 0].a):
    print(a)

0
1
2

## Pandas based Bellman

In [34]:
"""
두 클라스를 공통인 MDP에서 상속하게 만듬. 
L은 list를 이용하는 방식이고 PD는 pandas를 이용하는 방식임.
두 방식에 충돌이 나는 경우, 기반이 되는 MDP에는 공통 요소만 남기고 나머지는 MDP_L에 옮겨둘 예정임.
"""
class MDP_L(MDP):
    def __init__(self):
        super().__init__()

class MDP_PD(MDP):
    def __init__(self):
        super().__init__()
        
MDP_L().test()

Policy: [array([0.5, 0.5]), array([0.5, 0.5]), array([0.5, 0.5]), array([0.5, 0.5])]
v[0]=-2.5057415905523253
v[1]=-1.6060272426565467
v[2]=2.4316473139847745
v[3]=7.135350237940245
v[4]=0.0
q[0][0]=-3.3266059231766705
q[0][1]=-1.6848772579279794
q[1][0]=-3.3516633390821924
q[1][1]=0.13960885376910126
q[2][0]=0.0
q[2][1]=4.863294627969549
q[3][0]=4.270700475880492
q[3][1]=10.0